mask_recognition/urls.py
from django.contrib import admin
from django.urls import path, re_path
from web import views

urlpatterns = [
    path('account/warnings/', views.warnings),

    path('account/employees/edit/<int:emp_id>/update/', views.update_employee),
    path('account/employees/edit/<int:emp_id>/', views.edit_employee),
    path('account/employees/delete/<int:emp_id>/', views.delete_employee),
    path('account/employees/add/', views.add_employee),
    path('account/employees/', views.employees),

    path('account/areas/camera/<int:cam_id>/delete/', views.delete_camera),
    path('account/areas/camera/<int:cam_id>/update/', views.update_camera),
    path('account/areas/camera/<int:cam_id>/', views.edit_camera),
    path('account/areas/edit/<int:area_id>/update/', views.update_area),
    path('account/areas/edit/<int:area_id>/', views.edit_area),
    path('account/areas/delete/<int:area_id>/', views.delete_area),
    path('account/areas/add_area/', views.add_area),
    path('account/areas/add_camera/', views.add_camera),
    path('account/areas/', views.areas),
    
    path('account/schedules/edit/<int:sched_id>/update/', views.update_schedule),
    path('account/schedules/edit/<int:sched_id>/', views.edit_schedule),
    path('account/schedules/delete/<int:sched_id>/', views.delete_schedule),
    path('account/schedules/add/', views.add_schedule),
    path('account/schedules/', views.schedules),

    path('account/backups/', views.backups),
    path('account/run_mask/', views.mask_detecting),
    path('account/backups/delete/<backup_name>/', views.delete_backup),
    path('account/backups/import/<backup_name>/', views._import),
    path('account/backups/export/', views.export),

    path('account/', views.account),

    path('admin/<int:account_id>/employees/<int:employee_id>/', views.admin_employee),
    path('admin/<int:account_id>/', views.detailed_account),

    path('admin/edit/<int:account_id>/update_account/', views.update_account),
    path('admin/edit/<int:account_id>/', views.edit_account),
    path('admin/delete/<int:account_id>/', views.delete_account),
    path('admin/', views.admin),

    path('contacts/', views.contacts),
    path('register/', views.register),
    
    re_path(r'.*ukr/', views.ukr),
    re_path(r'.*eng/', views.eng),

    re_path(r'.*contacts_redirect/', views.contacts_redirect),
    re_path(r'.*backups_redirect/', views.backups_redirect),
    re_path(r'.*registration/', views.registration),
    re_path(r'.*signout/', views.signout),
    path('signin/', views.signin),
    path('', views.index),
]

web/forms.py
from django import forms

class signInForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()

class signUpForm(forms.Form):
    mgr_name = forms.CharField(label="Manager name")
    mgr_surname = forms.CharField(label="Manager surname")
    mgr_father = forms.CharField(label="Manager father name")
    mgr_birth = forms.DateField(label="Manager birthday")
    mgr_phone = forms.CharField(label="Manager phone number")
    mgr_email = forms.EmailField(label="Manager email")
    org_name = forms.CharField(label="Company name")
    org_adress = forms.CharField(label="Company adress")
    password = forms.CharField(label="Manager password")
    password_again = forms.CharField(label="Manager password (again)")

templates/en/account.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h1>{{manager.name}} {{manager.surname}} {{manager.father}}</h1>
        <h3>{{organization.name}}</h3>
        <table>
            <tr>
                <td class="tb-title">
                    Adress:
                </td>
                <td class="tb-cnt">
                    {{organization.adress}}
                </td>
            </tr>
            <tr>
                <td class="tb-title">
                    Birth date:
                </td>
                <td class="tb-cnt">
                    {{manager.birth}}
                </td>
            </tr>
            <tr>
                <td class="tb-title">
                    Email:
                </td>
                <td class="tb-cnt">
                    {{manager.email}}
                </td>
            </tr>
            <tr>
                <td class="tb-title">
                    Tel.:
                </td>
                <td class="tb-cnt">
                    {{manager.phone}}
                </td>
            </tr>
        </table>
        <ul>
            <li><a href="employees/">Employees</a></li>
            <li><a href="schedules/">Schedules</a></li>
            <li><a href="areas/">Areas and Cameras</a></li>
            <li><a href="warnings/">Warnings</a></li>
        </ul>
        <a id="btn-run" href="run_mask/">Run Mask Detecting</a>
    </div>
</div>
{% endblock content %}

templates/en/admin.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h1>
            Admin page
        </h1>
        <div>
            <table class="tb-with-list">
                <caption id="tb-cap">Managers and Organizations</caption>
                <tr>
                    <th class="tb-td">Manager Name</th>
                    <th class="tb-td">Manager Surname</th>
                    <th class="tb-td">Manager email</th>
                    <th class="tb-td">Manager phone</th>
                    <th class="tb-td">Organization</th>
                    <th class="tb-td">Organization adress</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                {% for item in items %}
                <tr>
                    <td class="tb-td">{{item.name}}</td>
                    <td class="tb-td">{{item.surname}}</td>
                    <td class="tb-td">{{item.email}}</td>
                    <td class="tb-td">{{item.phone}}</td>
                    <td class="tb-td">{{item.org_name}}</td>
                    <td class="tb-td">{{item.org_adress}}</td>
                    <td class="tb-td edit-bck"><a class="hover-btn" href="edit/{{item.id}}/">Edit</a></td>
                    <td class="tb-td del-bck"><a class="hover-btn" href="delete/{{item.id}}/">Delete</a></td>
                    <td class="tb-td det-bck"><a class="hover-btn" href="{{item.id}}/">Details</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/en/area.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h3>Edit an area</h3>
        <form action="update/" method="post">
            {% csrf_token %}
            <label for="area_name">Area name:</label><br>
            <div class="input-div">
                <input type="text" name="area_name" id="id_area_name" required value="{{area.name}}" placeholder="Area 1">
            </div>
            <input class="sbmt-btn" type="submit" value="Update">
        </form>
    </div>
</div>   
{% endblock content %}

templates/en/areas.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <table class="tb-with-list">
            <caption id="tb-cap">Areas and Cameras list</caption>
            <tr>
                <th class="tb-td">ID</th>
                <th class="tb-td">Area name</th>
                <th class="tb-td">Сameras</th>
                <th></th>
                <th></th>
            </tr>
            {% for area in areas %}
            <tr>
                <td class="tb-td">
                    {{area.id}}
                </td>
                <td class="tb-td">
                    {{area.name}}
                </td>
                <td class="tb-td">
                    {% for camera in area.cameras_dict %}
                        <a class="cam" href="camera/{{camera.id}}/">{{camera.name}}</a><br>
                    {% endfor %}
                </td>
                <td class="tb-td edit-bck">
                    <a class="hover-btn" href="edit/{{area.id}}/">Edit</a>
                </td>
                <td class="tb-td del-bck">
                    <a class="hover-btn" href="delete/{{area.id}}/">Delete</a>
                </td>
            {% endfor %}
        </table>
        <h3>Add new area</h3>
        <form action="add_area/" method="post">
            {% csrf_token %}
            <label for="area_name">Area name:</label><br>
            <div class="input-div">
                <input type="text" name="area_name" id="id_area_name" required placeholder="Area 1">
            </div>
            <input class="sbmt-btn" type="submit" value="Add">
        </form>
    
        <h3>Add new camera</h3>
        <form action="add_camera/" method="post">
            {% csrf_token %}
            <label for="camera_name">Camera name:</label><br>
            <div class="input-div">
                <input type="text" name="camera_name" id="id_camera_name" required placeholder="Camera 1">
            </div>
            <label for="camera_for_area_name">Area name:</label><br>
            <div class="input-div">
                <select class="select-input" name="camera_for_area_name" id="id_camera_for_area_name" required>
                    {% for area in areas %}
                        <option value="{{area.name}}">{{area.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <input class="sbmt-btn" type="submit" value="Add">
        </form>
    </div>
</div>
{% endblock content %}

templates/en/backups.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <table class="tb-with-list">
            <caption  id="tb-cap">Backups</caption>
            <tr>
                <th class="tb-td">Backup name</th>
                <th class="tb-td">Backup datetime</th>
                <th></th>
                <th></th>
            </tr>
            {% for backup in backups %}
            <tr>
                <td class="tb-td">{{backup.name}}</td>
                <td class="tb-td">{{backup.time}}</td>
                <td class="tb-td edit-bck"><a class="hover-btn" href="import/{{backup.name}}/">Import</a></td>
                <td class="tb-td del-bck"><a class="hover-btn" href="delete/{{backup.name}}/">Delete</a></td>
            </tr>
            {% endfor %}
        </table>
        <button class="del-cam exp" onclick="window.location='export/'">Export</button>
    </div>
</div>
{% endblock content %}

templates/en/base.html
<!DOCTYPE html>
{% load static %}
{% load googlecharts %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{{title}}</title>
</head>
<body>
    {% block header %}
    <header>
        <a class="nav" href="/">Home</a>
        <a class="nav" href="contacts_redirect/">Contacts</a>
        <a class="nav" href="backups_redirect/">Backups</a>
        <a class="nav" href="signout/">Sign Out</a>
        <div>
            <a class="nav" href="ukr/">UA</a> | 
            <a class="nav cur-lang" href="eng/">EN</a>
        </div>
    </header>
    {% endblock header %}
    <div class="wrapper">
        {% block content %}
            {% googlecharts %}
            {% endgooglecharts %}
        {% endblock content %}
    </div>
    <div class="errors">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
        </span>
            {% endfor %}
            </div>
        {% endif %}
    </div>
    <footer>
        <div id="reserved">
            All rights reserved!
        </div>
    </footer>
</body>
</html>

templates/en/camera.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h3>Edit camera</h3>
        <form action="update/" method="post">
            {% csrf_token %}
            <label for="camera_name">Camera name:</label><br>
            <div class="input-div">
                <input type="text" name="camera_name" id="id_camera_name" required value="{{camera.name}}" placeholder="Camera 1">
            </div>
            <label for="camera_for_area_name">Area name:</label><br>
            <div class="input-div">
                <select name="camera_for_area_name" id="id_camera_for_area_name">
                    {% for area in areas %}
                        <option value="{{area.name}}"{% if camera.area_id == area.id %} selected {% endif %}>{{area.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <input class="sbmt-btn" type="submit" value="Update">
            
        </form>
        <button class="del-cam" onclick="window.location='delete/'">Delete</button>
    </div>
</div>
{% endblock content %}

templates/en/contacts.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt" style="width: 50%;">
        <h1>Contacts</h1>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Beatae impedit veniam quisquam molestias eius at quis cumque 
            alias eos accusamus consequatur, culpa numquam. Quis deleniti excepturi fugit ea dolore delectus?
        </p>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Beatae impedit veniam quisquam molestias eius at quis cumque 
            alias eos accusamus consequatur, culpa numquam. Quis deleniti excepturi fugit ea dolore delectus?
        </p>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Beatae impedit veniam quisquam molestias eius at quis cumque 
            alias eos accusamus consequatur, culpa numquam. Quis deleniti excepturi fugit ea dolore delectus?
        </p>
    </div>
</div>
{% endblock content %}

templates/en/edit_account.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h1>Edit a manager</h1>
        <form action="update_account/" method="post">
            {% csrf_token %}

            <label for="id_mgr_name">Manager name:</label>
            <div class="input-div">
                <input type="text" name="mgr_name" id="id_mgr_name" required value={{manager.name}} placeholder="Ivan">
            </div>

            <label for="id_mgr_surname">Manager surname:</label>
            <div class="input-div">
                <input type="text" name="mgr_surname" id="id_mgr_surname" required value={{manager.surname}} placeholder="Ivanov">
            </div>
            
            <label for="id_mgr_father">Manager father name:</label>
            <div class="input-div">
                <input type="text" name="mgr_father" id="id_mgr_father" required value={{manager.father}} placeholder="Ivanovich">
            </div>

            <label for="id_mgr_birth">Manager birthday:</label>
            <div class="input-div">
                <input type="text" name="mgr_birth" id="id_mgr_birth" required value='{{manager.birth}}' placeholder="1990-01-25">
            </div>

            <label for="id_mgr_phone">Manager phone number:</label>
            <div class="input-div">
                <input type="text" name="mgr_phone" id="id_mgr_phone" required value='{{manager.phone}}' placeholder="+380 123 45 67 89">
            </div>

            <label for="id_mgr_email">Manager email:</label>
            <div class="input-div">
                <input type="email" name="mgr_email" id="id_mgr_email" required value={{manager.email}} placeholder="email@mail.com">
            </div>

            <label for="id_org_name">Company name:</label>
            <div class="input-div">
                <input type="text" name="org_name" id="id_org_name" required value='{{organization.name}}' placeholder="Apple Inc.">
            </div>

            <label for="id_org_adress">Company adress:</label>
            <div class="input-div">
                <input type="text" name="org_adress" id="id_org_adress" required value='{{organization.adress}}' placeholder="Moscow Ave. 234">
            </div>

            <label for="id_password">Manager password:</label>
            <div class="input-div">
                <input type="password" name="password" id="id_password" required placeholder="123456">
            </div>

            <label for="id_password_again">Manager password (again):</label>
            <div class="input-div">
                <input type="password" name="password_again" id="id_password_again" required placeholder="123456">
            </div>
            <input class="sbmt-btn" type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock content %}

templates/en/employee_a.html
{% extends "en/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h1>Organization: {{organization.name}}</h1>
        <h3>Employee info:</h3>
        <div><b>Name: </b>{{employee.name}}</div>
        <div><b>Surname: </b>{{employee.surname}}</div>
        <div><b>Father name: </b>{{employee.father}}</div>
        <div><b>Birthday: </b>{{employee.birth}}</div>
        <div><b>Phone number: </b>{{employee.phone}}</div>
        <div><b>Schedule: </b>{{schedule.time_start}} - {{schedule.time_end}} (
            {% if schedule.monday %}
                Mon
            {% endif %}
            {% if schedule.tuesday %}
                Tue
            {% endif %}
            {% if schedule.wednesday %}
                Wed
            {% endif %}
            {% if schedule.thursday %}
                Thu
            {% endif %}
            {% if schedule.friday %}
                Fri
            {% endif %}
            {% if schedule.saturday %}
                Sat
            {% endif %}
            {% if schedule.sunday %}
                Sun
            {% endif %}
            )</div>
    </div>
</div> 
{% endblock content %}

templates/en/employees.html
{% extends "en/base.html" %}
{% block content %}
    <div id="content">
        <div id="page-inner-cnt">
            <table class="tb-with-list">
                <caption id="tb-cap">Employees list</caption>
                <tr>
                    <th class="tb-td">Name</th>
                    <th class="tb-td">Surname</th>
                    <th class="tb-td">Father</th>
                    <th class="tb-td">Birthday</th>
                    <th class="tb-td">Phone number</th>
                    <th class="tb-td">Email</th>
                    <th class="tb-td">Schedule</th>
                    <th></th>
                    <th></th>
                </tr>
                {% for employee in employees %}
                <tr>
                    <td class="tb-td">
                        {{employee.name}}
                    </td>
                    <td class="tb-td">
                        {{employee.surname}}
                    </td>
                    <td class="tb-td">
                        {{employee.father}}
                    </td>
                    <td class="tb-td">
                        {{employee.birth}}
                    </td>
                    <td class="tb-td">
                        {{employee.phone}}
                    </td>
                    <td class="tb-td">
                        {{employee.email}}
                    </td>
                    <td class="tb-td">
                        {{employee.sched_dict.time_start}} - {{employee.sched_dict.time_end}} (
                        {% if employee.sched_dict.monday %}
                            Mon
                        {% endif %}
                        {% if employee.sched_dict.tuesday %}
                            Tue
                        {% endif %}
                        {% if employee.sched_dict.wednesday %}
                            Wed
                        {% endif %}
                        {% if employee.sched_dict.thursday %}
                            Thu
                        {% endif %}
                        {% if employee.sched_dict.friday %}
                            Fri
                        {% endif %}
                        {% if employee.sched_dict.saturday %}
                            Sat
                        {% endif %}
                        {% if employee.sched_dict.sunday %}
                            Sun
                        {% endif %}
                        )
                    </td>
                    <td class="tb-td edit-bck"><a class="hover-btn" href="edit/{{employee.id}}/">Edit</a></td>
                    <td class="tb-td del-bck"><a class="hover-btn" href="delete/{{employee.id}}/">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
            <h3>Add new employee</h3>
            <form action="add/" method="post">
                {% csrf_token %}
                <label for="emp_name">Employee name:</label><br>
                <div class="input-div">
                    <input type="text" name="emp_name" id="id_emp_name" required placeholder="Ivan">
                </div>
                <label for="emp_surname">Employee surname:</label><br>
                <div class="input-div">
                    <input type="text" name="emp_surname" id="id_emp_surname" required placeholder="Ivanov">
                </div>
                <label for="emp_father">Employee father:</label><br>
                <div class="input-div">
                    <input type="text" name="emp_father" id="id_emp_father" required placeholder="Ivanovich">
                </div>
                <label for="emp_birth">Birthday:</label><br>
                <div class="input-div">
                    <input type="text" name="emp_birth" id="id_emp_birth" required placeholder="1980-12-12">
                </div>
                <label for="emp_phone">Phone number:</label><br>
                <div class="input-div">
                    <input type="tel" name="emp_phone" id="id_emp_phone" required placeholder="+380 12 345 67 89">
                </div>
                
                <label>Schedule:</label><br>
                <div class="input-div">
                    {% for sched in schedules %}  
                        <input class="radio-btn" type="radio" name="emp_sched" id="id_emp_sched" value={{sched.id}} checked>                  
                        <label for="emp_sched">{{sched.time_start}} - {{sched.time_end}} (
                                {% if sched.monday %}
                                    Mon
                                {% endif %}
                                {% if sched.tuesday %}
                                    Tue
                                {% endif %}
                                {% if sched.wednesday %}
                                    Wed
                                {% endif %}
                                {% if sched.thursday %}
                                    Thu
                                {% endif %}
                                {% if sched.friday %}
                                    Fri
                                {% endif %}
                                {% if sched.saturday %}
                                    Sat
                                {% endif %}
                                {% if sched.sunday %}
                                    Sun
                                {% endif %}
                                )</label><br>                       
                        {% endfor %}
                </div>
                <label for="emp_email">Email:</label><br>
                <div class="input-div">
                    <input type="email" name="emp_email" id="id_emp_email" required placeholder="email@mail.com">
                </div>
                <label for="emp_password">Password:</label><br>
                <div class="input-div">
                    <input type="text" name="emp_password" id="id_emp_password" required placeholder="123456">
                </div>
                <label for="emp_password_again">Password (again):</label><br>
                <div class="input-div">
                    <input type="text" name="emp_password_again" id="id_emp_password_again" required placeholder="123456">
                </div>
                <input class="sbmt-btn" type="submit" value="Add">
            </form>
        </div>
        
    </div>
{% endblock content %}

templates/en/index.html
{% extends "en/base.html" %}
{% block content %}
<div id="signin-form">
    <div class="form-back">
        <form action="signin/" method="post" novalidate>
            {% csrf_token %}
            <label for="email">Email:</label><br>
            <div class="input-div">
                <input type="email" name="email" id="id_email" placeholder="email@mail.com">
            </div>
            <label for="password">Password:</label><br>
            <div class="input-div">
                <input type="password" name="password" id="id_password" placeholder="123456">
            </div>
            <input class="sbmt-btn" type="submit" value="Sign In">
            <a id="reg-a" href="register/">Register</a>
        </form>
    </div>
</div>
{% endblock content %}

templates/ua/edit_account.html
{% extends "ua/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h1>Редагування керівника</h1>
        <form action="update_account/" method="post">
            {% csrf_token %}

            <label for="id_mgr_name">Ім'я керівника:</label>
            <div class="input-div">
                <input type="text" name="mgr_name" id="id_mgr_name" required value={{manager.name}} placeholder="Іван">
            </div>

            <label for="id_mgr_surname">Прізвище керівника:</label>
            <div class="input-div">
                <input type="text" name="mgr_surname" id="id_mgr_surname" required value={{manager.surname}} placeholder="Іванов">
            </div>
            
            <label for="id_mgr_father">По батькові керівника:</label>
            <div class="input-div">
                <input type="text" name="mgr_father" id="id_mgr_father" required value={{manager.father}} placeholder="Іванович">
            </div>

            <label for="id_mgr_birth">Дата народження:</label>
            <div class="input-div">
                <input type="text" name="mgr_birth" id="id_mgr_birth" required value='{{manager.birth}}' placeholder="1990-01-25">
            </div>

            <label for="id_mgr_phone">Номер телефону:</label>
            <div class="input-div">
                <input type="text" name="mgr_phone" id="id_mgr_phone" required value='{{manager.phone}}' placeholder="+380 123 45 67 89">
            </div>

            <label for="id_mgr_email">Електрона пошта:</label>
            <div class="input-div">
                <input type="email" name="mgr_email" id="id_mgr_email" required value={{manager.email}} placeholder="email@mail.com">
            </div>

            <label for="id_org_name">Назва компанії:</label>
            <div class="input-div">
                <input type="text" name="org_name" id="id_org_name" required value='{{organization.name}}' placeholder="Apple Inc.">
            </div>

            <label for="id_org_adress">Адреса компанії:</label>
            <div class="input-div">
                <input type="text" name="org_adress" id="id_org_adress" required value='{{organization.adress}}' placeholder="просп. Московський 234">
            </div>

            <label for="id_password">Пароль:</label>
            <div class="input-div">
                <input type="password" name="password" id="id_password" required placeholder="123456">
            </div>

            <label for="id_password_again">Повторіть пароль:</label>
            <div class="input-div">
                <input type="password" name="password_again" id="id_password_again" required placeholder="123456">
            </div>
            <input class="sbmt-btn" type="submit" value="Оновити">
        </form>
    </div>
</div>
{% endblock content %}

templates/ua/register.html
{% extends "ua/base.html" %}
{% block content %}
<div id="content">
    <div id="page-inner-cnt">
        <h1>Реєстрація</h1>
        <form action="registration/" method="post">
            {% csrf_token %}
            <label for="id_mgr_name">Ім'я керівника:</label>
            <div class="input-div">
                <input type="text" name="mgr_name" required id="id_mgr_name" placeholder="Іван">
            </div>
            <label for="id_mgr_surname">Прізвище керівника:</label>
            <div class="input-div">
                <input type="text" name="mgr_surname" required id="id_mgr_surname" placeholder="Іванов">
            </div>
            <label for="id_mgr_father">По батькові керівника:</label>
            <div class="input-div">
                <input type="text" name="mgr_father" required id="id_mgr_father" placeholder="Іванович">
            </div>
            <label for="id_mgr_birth">Дата народження:</label>
            <div class="input-div">
                <input type="text" name="mgr_birth" required id="id_mgr_birth" placeholder="1990-12-23">
            </div>
            <label for="id_mgr_phone">Номер телефону:</label>
            <div class="input-div">
                <input type="text" name="mgr_phone" required id="id_mgr_phone" placeholder="+380 123 45 67 89">
            </div>
            <label for="id_mgr_email">Електрона пошта:</label>
            <div class="input-div">
                <input type="email" name="mgr_email" required id="id_mgr_email" placeholder="email@mail.com">
            </div>
            <label for="id_org_name">Назва компанії:</label>
            <div class="input-div">
                <input type="text" name="org_name" required id="id_org_name" placeholder="Apple Inc.">
            </div>
            <label for="id_org_adress">Адреса компанії:</label>
            <div class="input-div">
                <input type="text" name="org_adress" required id="id_org_adress" placeholder="просп. Московський 234">
            </div>
            <label for="id_password">Пароль:</label>
            <div class="input-div">
                <input type="text" name="password" required id="id_password" placeholder="123456">
            </div>
            <label for="id_password_again">Повторіть пароль:</label>
            <div class="input-div">
                <input type="text" name="password_again" required id="id_password_again" placeholder="123456">
            </div>
            <input class="sbmt-btn" type="submit" value="Зареєструватися">
        </form>
        <a class="del-cam" href="/">Увійти</a>
    </div>
</div>
{% endblock content %}